### ISSUE TITLE
Reload systemd after modifying fstab

### ISSUE THREAD

**Issue by zeha** [grml/grml-autoconfig#12]
On grml64-full 2022.11-rc1, mount(1) shows a warning about systemd using old data for /etc/fstab:

```
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use `systemctl daemon-reload` to reload.
```

I think (but am not sure) this is "caused" by grml-autoconfig updating /etc/fstab, but not reloading systemd.

**Comment by mika** [comment]
Nice catch, thanks for reporting! :)
Should be fixed with grml-udev-config v0.6.0
